### ISSUE TITLE
Jerakia 2.0 headline items.

### ISSUE THREAD

**Issue by crayfishx** [crayfishx/jerakia#77]
# Jerakia 2.0

This is a heads up about some of the changes in the next release, it will be a semver major bump because there are some deprecations and some default changes - however, nothing you can currently do in 1.2 will stop working in 2.0 - although small configuration changes / gem installations may be required.  There will be no breaking changes to policy files and how they are written.   The breakdown currently is;

### Keyless lookups

The biggest change is to allow for Jerakia lookups to be keyless, that is, for a datasource to have the ability to provide a data hash of all keys in all namespaces in one hit, while still following the hierarchical structure and obeying schema directives such as hash merges.  This will enable tools like Puppet to perform one single hit against the Jerakia API per Puppet run,  which should massively increase performance.  This also opens up the possibility to integrate with tools that don't have the concept of a per key lookup, the first of which being Ansible.  The current concept of a single key lookup will remain unaffected and will work as it does in 1.2

### Vault transit as the default encryption

The encryption output filter will support providers, users currently working with the existing eyaml based encryption will need to change `output_filter :encryption` to `output_filter :encryption, :provider => :eyaml`.  The default provider, if none is given, will use vault transit as a 'encryption as a service' to perform decryption of encrypted keys from data sources.  This will also become a bit of a first class citizen by adding an `encrypt` sub-command to the Jerakia CLI to allow for easy encryption of data using the pre-configured keys.

### New datasource API

This is a breaking change, and existing datasources will not work with Jerakia 2.0 - we don't believe there are any third party datasources in the public domain, but if you are working with in-house data sources they will need to be updated.  The new datasource API will solve some performance issues and make it a lot easier to write and share new datasources.  This will also add some features to datasources such as the ability to advertise capabilities (such as keyless) and record "explain" information for lookup strategies.

### Removal of all Puppet integrations from Jerakia core.

Jerakia currently ships with a Hiera 3.x backend and a puppet `data_binding_terminus` within the core.  These will be removed from the core repo and made available in a separate library provided in https://github.com/crayfishx/jerakia-puppet.  This library will continue to be supported to provide "legacy" integration to Puppet at least until Puppet 4.0 is end of life.  Users of Puppet 4.9+ should use the Hiera 5 backend that will be provided in the Jerakia Puppet module (https://forge.puppet.com/crayfishx/jerakia) to integrate with Jerakia server

### Standardisation of default logfile and db locations

Although still configurable, database files (sqlite3) and log files will default to `/var/db/jerakia` and `/var/log/jerakia/jerakia.log` respectively.

**Comment by beddari** [comment]
Thanks, this clears up a few questions for me!
