### ISSUE TITLE
HTTP datasource broken in master

### ISSUE THREAD

**Issue by drbrerv** [crayfishx/jerakia#81]
I have done some modifications to a copy of lib/jerakia/datasource/http.rb to "restore it to working order" since it was throwing exceptions/errors in running command-line lookups against a simply-configured CouchDB instance.  Since I have been using version 2.0.1 for this, those changes can be committed to the experimental/2.0 branch--or wherever else they might be helpful.

**Comment by crayfishx** [comment]
Hi @drbrerv - there was a push missing which meant the http datasource didn't get updated to the new datasource API in 2.0 - I can't see your modifications anywhere - I've got a PR in #82  which should solve the issue but this is so far untested.....

**Comment by drbrerv** [comment]
Hi @crayfishx.  I have a new branch (feature/drbrerv_http_datasource ...feel free to not like the name) with my lightly-tested updates for the HTTP datasource.  I tried to push to the repo just now, but didn't have permissions.

**Comment by crayfishx** [comment]
@drbrerv yes you would need to do it as a Pull Request against the master branch of the main repo (I can't see that you've actually forked the repo?)

If not - feel free to send me the code by email (craig@craigdunn.org) - although it would be great if you could test the patch in #82 too

**Comment by crayfishx** [comment]
Hi @drbrerv  - in the end this should be fixed in #82 which has now been released, so I'm going to close off #84 as a duplicate - but thank you very much for your contribution...... FYI in future PR's should be raised against the master branch.

If you upgrade to the latest version the HTTP data source should be correct now.

Thanks again
